services:
  accounts:
    image: "eabandara/myspace-products:0.0.1"
    container_name: myspace-products-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - myspace
networks:
  myspace:
    driver: "bridge"